### PR TITLE
updated license data to SPDX license list v3.4

### PR DESCRIPTION
**Pull request by Chinmay-Gurjar**
This is the updated license list of SPDX license list v3.4.
The license text field is filled with the license text in the SPDX website.
please review it @zvr.

### CODE REVIEW

**Comment by zvr** [comment]
why is there also a change of the database link?

**Comment by Chinmay-Gurjar** [comment]
> why is there also a change of the database link?

it's because I am using sqlite instead of mysql for Database.

**Comment by zvr** [comment]
You may use whatever DB you want in your environment, but this is no reason to change it in the master repo.

**Comment by zvr** [comment]
Have you tested that this csv file is read OK and saved in the database?

**Comment by Chinmay-Gurjar** [comment]
Yes.

**Comment by zvr** [comment]
The data are wrong -- according to this CSV all licenses are not OSI approved and not FSF Free/libre.

**Comment by Chinmay-Gurjar** [comment]
I am getting some conflict errors it may be due to migration, I'll be closing this PR and getting a new one.
Sorry.

**Pull request closed without merging**
